@echo off
echo Starting ECG Prediction Application...

echo Installing Python dependencies...
pip install -r requirements.txt

echo Installing Node.js dependencies...
npm install

echo Starting Flask backend...
start "Flask Backend" python app.py

echo Waiting for backend to start...
timeout /t 3

echo Starting React frontend...
start "React Frontend" npm run dev

echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:5173
pause